name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install
      run: make install
      
    - name: lint
      run: make lint
      
    - name: Run check
      run: make test
      
    - name: format  
      run: make format
